#!/bin/bash

if [ -z $1 ]; then
	echo "No className given."
	exit 1
fi

className=I$(echo ${1}| sed 's/\(.\)/\U\1/')
fileName=${className}
gaurdName=$(echo ${className}| tr '[:lower:]' '[:upper:]')
location=${2+"${2}/"}


cat << _EOF_ >> ${location}${fileName}.hpp
#ifndef ${gaurdName}_HPP
#define ${gaurdName}_HPP

class ${className};
class ${className}
{
public:
	virtual ~${className}() {};
};
#endif
_EOF_