#!/bin/bash

if [ -z $1 ]; then
	echo "No className given."
	exit 1
fi

className=S$(echo ${1}| sed 's/\(.\)/\U\1/')
fileName=${className}
gaurdName=$(echo ${className}| tr '[:lower:]' '[:upper:]')
location=${2+"${2}/"}


cat << _EOF_ >> ${location}${fileName}.hpp
#ifndef ${gaurdName}_HPP
#define ${gaurdName}_HPP

class ${className};
class ${className}
{
private:
	${className}();
	static ${className}* a_oInstance;
public:
	~${className}();
	static ${className}* GetInstance();
};
#endif
_EOF_

cat << _EOF_ >> ${location}${fileName}.cpp
#include "${fileName}.hpp"

${className}* ${className}::a_oInstance = 0;

${className}::${className}()
{

}

${className}::~${className}()
{

}

${className}* ${className}::GetInstance()
{
	if(a_oInstance) { return a_oInstance; }
	a_oInstance = new ${className}();
	return a_oInstance;
}
_EOF_